source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'ruby-net-ldap', :require => 'net/ldap'
gem 'icalendar'
gem 'chronic'
gem 'authlogic'
gem 'ar_mailer', :require => 'action_mailer/ar_mailer'
gem 'whenever'
gem 'airbrake'
gem 'activerecord-mysql2-adapter'
gem 'mysql2'
gem 'vestal_versions', git: 'https://github.com/laserlemon/vestal_versions.git'
gem 'rdoc', '~> 3.6.1'
gem 'paperclip'
gem 'htmlentities'
gem 'capistrano'
gem 'htmlentities'
gem 'simple_form'
# gem 'jazz_hands'
gem 'letter_opener', :group => :development
gem 'pry-rails', :group => :development
gem 'mail'
gem 'delayed_job_active_record'
gem 'delayed_job_web'
#authentication
gem 'rubycas-client-rails'
gem 'rubycas-client', '2.2.1'
