source :rubygems
gem "rails", "2.3.12"
gem "ruby-net-ldap", :require => "net/ldap"
gem "fastercsv"
gem "icalendar"
gem "prawn"
gem "chronic"
gem "has_many_polymorphs"
gem "authlogic"
gem "ar_mailer", :require => "action_mailer/ar_mailer"
gem "whenever"
gem "hoptoad_notifier"
gem "mysql"
gem "vestal_versions"
gem "rdoc", "~> 3.6.1"
gem "paperclip", "~> 2.3.15"
gem "capistrano"